layout_spectrum: 0.483372
color:
  saturation: 0.8553191
  lightness: 0.8212766
  brandStrength: 0.8191935
  brandColors:
    - '#020202'
    - '#F2F2F2'
    - '#838383'
    - '#85ABC4'
    - '#FFCE00'
  rhythmicContrast: 0.5212766
typography_spectrum: 0.1851064
name: Besognes.com
